version: '3.8'

services:


  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"

  web:
    build: .
    container_name: fastapi_app
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      - db